apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
  tolerations:
    - key: "app"
      value: "nginx"
      operator: "Equal"
      effect: "NoSchedule"

